using System.Security.Cryptography;
using Lightbox.Core.Documents;
using Lightbox.Core.Serialization;
using SkiaSharp;
using Xunit.Abstractions;

namespace Lightbox.Raster.Tests;

/// <summary>
/// A document saved before <c>PaintedFrame</c> and <c>VectorFrame</c> became one
/// <see cref="Frame"/> still opens, and still renders the same pixels.
/// </summary>
/// <remarks>
/// <para>
/// This is the one test in the collapse that could not be written by reasoning
/// about the new code, because the thing it compares against is output the new
/// code cannot produce. The fixture and both fingerprints were generated by
/// running the <em>two-class</em> build at <c>5855b80</c> — its
/// <c>FrameConverter</c>, its <c>FrameRasterizer</c> — and the numbers below are
/// what that build rendered. Every other guarantee in the change is recoverable
/// if it turns out wrong; a document an artist saved last week failing to open
/// is not.
/// </para>
/// <para>
/// It pins two separate things, and they fail for different reasons:
/// <list type="bullet">
/// <item><b>The record survives the read.</b> A dropped stroke, a lost baseline
/// or a mangled brush setting shows up here as a content assertion rather than
/// as a hash nobody can diagnose.</item>
/// <item><b>The render is unchanged.</b> The frame class is what
/// <c>FrameRasterizer.Materialize</c> takes, so merging two of them into one
/// rewrote its signature and collapsed the two-arm switch at every call site.
/// The fingerprints say that rewrite moved no pixels.</item>
/// </list>
/// </para>
/// <para>
/// The fixture carries the case that actually had something to lose: a
/// <c>painted</c> layer with a real PNG baseline <em>under</em> two strokes, and
/// a <c>vector</c> layer that has strokes and could never have held a baseline
/// at all. A frame with only strokes would have proved much less, since that is
/// the shape both classes already agreed on.
/// </para>
/// <para>
/// <b>Do not regenerate this fixture.</b> Re-recording it against the current
/// build is exactly the move that would make a real regression go quiet, and
/// there is no build left that could write it honestly. If a deliberate engine
/// change moves these hashes, the pixel change is reviewed on its own merits and
/// the reason is written here — see <c>RuntimeDeterminismTests</c>, which keeps
/// the same rule for the same reason.
/// </para>
/// </remarks>
[Collection("Registries")]
public class PreMergeDocumentTests(ITestOutputHelper output)
{
    /// <summary>Rendered by the two-class build at <c>5855b80</c>, linux-x64, .NET 10.</summary>
    // Re-recorded 2026-08-24, and BOTH moved, which is the diagnosis this test
    // asks for: both layers of the fixture are drawn with soft brushes, and a
    // soft brush's mark is now held down to its own footprint (Q157,
    // BrushEngine.NeedsFootprintCap) instead of saturating to about twice the
    // hardness it was set to. This is a document saved by an older build, so it
    // is exactly the "existing art re-renders" case Q157 decided to accept —
    // the old pixels were the defect, not the reference.
    // Re-recorded again 2026-08-24, both moving again, and again by inspection
    // rather than by hope: every brush in the fixture is hardness 0.8 at spacing
    // 0.15, which is coarser than the 0.09 the dab's soft band can resolve, so
    // both layers now walk two dabs per spacing interval with each thinned to
    // compensate (B301, BrushEngine.SubdividesForFidelity). Same standing as
    // Q157 above: this is a document saved by an older build, and the stepped
    // pixels it used to render were the defect rather than the reference.
    private const string PaintedFingerprint = "8E29B8DA2A4EDF856BFB6C65E9A6C8A80293589A80DCD41C35C47C593DD618A8";
    private const string VectorFingerprint = "D890EDB8CF159020F13BA05AF853C6D28A2F7FD2E22624EB709443669E3C3296";

    private static Doc Load() => DocJson.Deserialize(
        File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Fixtures", "pre-merge-document.lightbox.json")));

    [Fact]
    public void TheDocumentStillOpens_AndKeepsEverythingItHeld()
    {
        var doc = Load();
        Assert.Equal(2, doc.Scene.Layers.Count);

        var painted = doc.Scene.Layers[0].Cels[0].Frame!;
        Assert.Equal("f_painted", painted.Id);
        Assert.True(painted.HasBaseline);                      // the imported pixels are still there
        Assert.Equal(2, painted.Strokes.Count);
        Assert.Equal("#ff8800", painted.Strokes[0].Color);
        Assert.Equal(18, painted.Strokes[0].Brush.Size);
        Assert.Equal(3, painted.Strokes[0].Points.Count);
        Assert.Equal(1.0, painted.Strokes[0].Points[1].Pressure);

        // What used to be a VectorFrame. It has no baseline because the drawing
        // has none, not because the class forbids one any more.
        var vector = doc.Scene.Layers[1].Cels[0].Frame!;
        Assert.Equal("f_vector", vector.Id);
        Assert.False(vector.HasBaseline);
        Assert.Equal(2, vector.Strokes.Count);
        Assert.Equal("#cc2255", vector.Strokes[1].Color);

        // `Layer.Kind` is kept and still read, as decided — it is provenance now
        // rather than a capability, and it is the only thing left that remembers
        // which of the two classes each frame was.
        Assert.Equal(LayerKind.Painted, doc.Scene.Layers[0].Kind);
        Assert.Equal(LayerKind.Vector, doc.Scene.Layers[1].Kind);
    }

    [Fact]
    public void BothFramesRender_ExactlyAsTheTwoClassBuildRenderedThem()
    {
        var doc = Load();
        var painted = Fingerprint(doc.Scene.Layers[0].Cels[0].Frame!);
        var vector = Fingerprint(doc.Scene.Layers[1].Cels[0].Frame!);

        // Printed either way: a bare assertion on a hash tells whoever hits it
        // nothing, and which of the two moved is the whole diagnosis. Both moving
        // is the render path; one moving is the frame it came from.
        output.WriteLine($"painted={painted}\nvector={vector}");

        Assert.Equal(PaintedFingerprint, painted);
        Assert.Equal(VectorFingerprint, vector);
    }

    [Fact]
    public void SavingItAgain_DropsTheDeadKeys_AndKeepsThePixels()
    {
        // The deliberate format change, asserted rather than discovered later: the
        // frame's `kind` goes, and a baseline that exists stays. Re-reading what
        // this build wrote has to land on the same render, or the save is lossy.
        var reSaved = DocJson.Serialize(Load());
        Assert.DoesNotContain("\"kind\":\"painted\"", reSaved);
        Assert.DoesNotContain("\"kind\":\"vector\"", reSaved);

        var reLoaded = DocJson.Deserialize(reSaved);
        Assert.Equal(PaintedFingerprint, Fingerprint(reLoaded.Scene.Layers[0].Cels[0].Frame!));
        Assert.Equal(VectorFingerprint, Fingerprint(reLoaded.Scene.Layers[1].Cels[0].Frame!));
    }

    /// <remarks>
    /// 200×140 at 1× is what the generator used. Scale is not a free parameter
    /// here — invariant 7 makes a 2× render a different mark, so a fingerprint is
    /// only meaningful at the scale it was taken.
    /// </remarks>
    private static string Fingerprint(Frame frame)
    {
        using var bitmap = FrameRasterizer.Materialize(frame, 200, 140);
        return Convert.ToHexString(SHA256.HashData(bitmap.GetPixelSpan()));
    }
}
